### ISSUE TITLE
Donutcraft crashing on startup in Windows 10

### ISSUE THREAD

**Issue by MashedPotatoe** [DoughnutDev/DonutCraft-Pack#4]
Hello, MashedPotats here (EVan66),

I'm encountering an issue which seems to happen during startup. The logs showed that something wrong went in loading the mods. I will attach a link to the log below. If you need more, tell me. I'm running Windows 10 on an "old" 2010 dell laptop.

Note: The error is at the bottom

Please fix,
MashedPotats

https://www.dropbox.com/s/7u38f084qiibtlx/fml-client-latest.log?dl=0

**Comment by DoughnutDev** [comment]
Hi this is due to you not running Java 8.

**Comment by MashedPotatoe** [comment]
I am afraid that I indeed am running java. My about java below

![image](https://cloud.githubusercontent.com/assets/9442368/9037144/c73a8c40-3a1a-11e5-9bc7-e16ed144e6c9.png)

**Comment by DoughnutDev** [comment]
Make sure it is selected in your Java Settings on ATLauncher.

**Comment by MashedPotatoe** [comment]
Thanks!!! Even though I had my environment variable PATH set to my jdk 8 bin, atlauncher was pointing towards jre7.
