### ISSUE TITLE
few errors with server side install.

### ISSUE THREAD

**Issue by andejx** [DoughnutDev/DonutCraft-Pack#7]
currently the server install from atlauncher downloads some 'clientside' mods which crash the server when you try to load it.
removing the jars for ;
- JourneyMap5.0.1_Unlimited_MC1.7.10.jar
- CustomMainMenu-MC1.7.10-1.4.jar

seems to fix it and lets the server side load up. thanks.

**Comment by OptimusDonut** [comment]
Yes I am aware of this I will fix this in 0.1.2 update. I have to find out what the command is for it to not download load it on the server files. Thanks for the reminder.

**Comment by DoughnutDev** [comment]
Fixed in the new update!
